// ============================================================
// DADOS SIMULADOS — FarmaGOIE
// Todos os dados abaixo são FICTÍCIOS para fins de demonstração.
// Não representam dados reais de pacientes ou sistemas oficiais.
// ============================================================

export const DOENCAS_PRIORITARIAS = [
  {
    id: "d1",
    nome: "Doenças Cardiovasculares",
    cid10: "I00-I99",
    casos_estimados: 248500,
    mortalidade_estimada: 18240,
    taxa_mortalidade: 7.3,
    custo_anual_estimado: 145000000,
    tendencia: "estavel" as const,
    criticidade: "critica",
    nivel_risco: "critico" as const,
    medicamentos_vinculados: 24,
    medicamentos_associados: 24,
  },
  {
    id: "d2",
    nome: "Neoplasias / Oncológicos",
    cid10: "C00-D48",
    casos_estimados: 42300,
    mortalidade_estimada: 14100,
    taxa_mortalidade: 33.3,
    custo_anual_estimado: 320000000,
    tendencia: "crescente" as const,
    criticidade: "critica",
    nivel_risco: "critico" as const,
    medicamentos_vinculados: 38,
    medicamentos_associados: 38,
  },
  {
    id: "d3",
    nome: "Transtornos Mentais / Comportamentais",
    cid10: "F00-F99",
    casos_estimados: 185000,
    mortalidade_estimada: 2100,
    taxa_mortalidade: 1.1,
    custo_anual_estimado: 78000000,
    tendencia: "crescente" as const,
    criticidade: "alta",
    nivel_risco: "alto" as const,
    medicamentos_vinculados: 19,
    medicamentos_associados: 19,
  },
  {
    id: "d4",
    nome: "Diabetes Mellitus",
    cid10: "E10-E14",
    casos_estimados: 310000,
    mortalidade_estimada: 4800,
    taxa_mortalidade: 1.5,
    custo_anual_estimado: 95000000,
    tendencia: "crescente" as const,
    criticidade: "critica",
    nivel_risco: "critico" as const,
    medicamentos_vinculados: 12,
    medicamentos_associados: 12,
  },
  {
    id: "d5",
    nome: "Doenças Respiratórias Crônicas",
    cid10: "J40-J47",
    casos_estimados: 128000,
    mortalidade_estimada: 3200,
    taxa_mortalidade: 2.5,
    custo_anual_estimado: 42000000,
    tendencia: "estavel" as const,
    criticidade: "alta",
    nivel_risco: "alto" as const,
    medicamentos_vinculados: 15,
    medicamentos_associados: 15,
  },
  {
    id: "d6",
    nome: "Doenças Infecciosas Prioritárias",
    cid10: "A00-B99",
    casos_estimados: 87600,
    mortalidade_estimada: 1850,
    taxa_mortalidade: 2.1,
    custo_anual_estimado: 56000000,
    tendencia: "decrescente" as const,
    criticidade: "media",
    nivel_risco: "medio" as const,
    medicamentos_vinculados: 28,
    medicamentos_associados: 28,
  },
];

export const MEDICAMENTOS_ESTRATEGICOS = [
  {
    id: "m1",
    nome: "Atorvastatina 20mg",
    principio_ativo: "Atorvastatina Cálcica",
    doenca: "Doenças Cardiovasculares",
    estoque_meses: 1.2,
    consumo_mensal: 48000,
    consumo_medio_mensal: 48000,
    risco: "critico" as const,
    dependencia_importacao: 85,
    preco_unitario: 0.42,
    custo_unitario: 0.42,
    fabricante_nacional: false,
    fornecedor_principal: "Importador direto — Índia/China",
  },
  {
    id: "m2",
    nome: "Metformina 850mg",
    principio_ativo: "Cloridrato de Metformina",
    doenca: "Diabetes Mellitus",
    estoque_meses: 4.8,
    consumo_mensal: 120000,
    consumo_medio_mensal: 120000,
    risco: "baixo" as const,
    dependencia_importacao: 40,
    preco_unitario: 0.18,
    custo_unitario: 0.18,
    fabricante_nacional: true,
    fornecedor_principal: "EMS S.A. — Santo André/SP",
  },
  {
    id: "m3",
    nome: "Insulina NPH 100UI/mL",
    principio_ativo: "Insulina Humana NPH",
    doenca: "Diabetes Mellitus",
    estoque_meses: 2.1,
    consumo_mensal: 28000,
    consumo_medio_mensal: 28000,
    risco: "alto" as const,
    dependencia_importacao: 70,
    preco_unitario: 12.5,
    custo_unitario: 12.5,
    fabricante_nacional: true,
    fornecedor_principal: "Bio-Manguinhos / Novo Nordisk",
  },
  {
    id: "m4",
    nome: "Bevacizumabe 25mg/mL",
    principio_ativo: "Bevacizumabe",
    doenca: "Neoplasias / Oncológicos",
    estoque_meses: 0.8,
    consumo_mensal: 420,
    consumo_medio_mensal: 420,
    risco: "critico" as const,
    dependencia_importacao: 100,
    preco_unitario: 1850.0,
    custo_unitario: 1850.0,
    fabricante_nacional: false,
    fornecedor_principal: "Roche — importação direta",
  },
  {
    id: "m5",
    nome: "Olanzapina 10mg",
    principio_ativo: "Olanzapina",
    doenca: "Transtornos Mentais",
    estoque_meses: 3.2,
    consumo_mensal: 18500,
    consumo_medio_mensal: 18500,
    risco: "medio" as const,
    dependencia_importacao: 60,
    preco_unitario: 1.85,
    custo_unitario: 1.85,
    fabricante_nacional: false,
    fornecedor_principal: "Cristália Prod. Químicos",
  },
  {
    id: "m6",
    nome: "Budesonida 200mcg",
    principio_ativo: "Budesonida",
    doenca: "Doenças Respiratórias Crônicas",
    estoque_meses: 2.8,
    consumo_mensal: 32000,
    consumo_medio_mensal: 32000,
    risco: "medio" as const,
    dependencia_importacao: 75,
    preco_unitario: 3.2,
    custo_unitario: 3.2,
    fabricante_nacional: false,
    fornecedor_principal: "AstraZeneca — importação",
  },
  {
    id: "m7",
    nome: "Tenofovir + Lamivudina",
    principio_ativo: "Tenofovir/Lamivudina",
    doenca: "Doenças Infecciosas",
    estoque_meses: 5.4,
    consumo_mensal: 8400,
    consumo_medio_mensal: 8400,
    risco: "baixo" as const,
    dependencia_importacao: 20,
    preco_unitario: 4.8,
    custo_unitario: 4.8,
    fabricante_nacional: true,
    fornecedor_principal: "Far-Manguinhos / Farmanguinhos",
  },
  {
    id: "m8",
    nome: "Trastuzumabe 150mg",
    principio_ativo: "Trastuzumabe",
    doenca: "Neoplasias / Oncológicos",
    estoque_meses: 1.5,
    consumo_mensal: 180,
    consumo_medio_mensal: 180,
    risco: "critico" as const,
    dependencia_importacao: 100,
    preco_unitario: 4200.0,
    custo_unitario: 4200.0,
    fabricante_nacional: false,
    fornecedor_principal: "Roche — importação direta",
  },
];

export const COMPRAS_PUBLICAS = [
  {
    id: "c1",
    numero_processo: "SES-GO/2024-001247",
    objeto: "Aquisição de Medicamentos Cardiovasculares",
    modalidade: "Pregão Eletrônico",
    valor_estimado: 8500000,
    valor_homologado: null as number | null,
    status: "em_andamento" as const,
    risco_atraso: "alto",
    fornecedores_habilitados: 3,
    data_abertura: "15/09/2024",
    data_homologacao: null as string | null,
    economia_estimada: 12.5,
  },
  {
    id: "c2",
    numero_processo: "SES-GO/2024-000892",
    objeto: "Insulina NPH — Demanda Anual",
    modalidade: "Ata SUS/MS",
    valor_estimado: 4200000,
    valor_homologado: 3850000,
    status: "concluido" as const,
    risco_atraso: "baixo",
    fornecedores_habilitados: 2,
    data_abertura: "01/07/2024",
    data_homologacao: "20/07/2024",
    economia_estimada: 8.3,
  },
  {
    id: "c3",
    numero_processo: "SES-GO/2024-002104",
    objeto: "Medicamentos Oncológicos — Bevacizumabe e Trastuzumabe",
    modalidade: "Pregão Eletrônico",
    valor_estimado: 22000000,
    valor_homologado: null as number | null,
    status: "atrasado" as const,
    risco_atraso: "alto",
    fornecedores_habilitados: 1,
    data_abertura: "02/10/2024",
    data_homologacao: null as string | null,
    economia_estimada: 0,
  },
  {
    id: "c4",
    numero_processo: "SES-GO/2024-001850",
    objeto: "Antipsicóticos Atípicos — Programa Saúde Mental",
    modalidade: "Dispensação Direta",
    valor_estimado: 3100000,
    valor_homologado: 2629000,
    status: "concluido" as const,
    risco_atraso: "medio",
    fornecedores_habilitados: 5,
    data_abertura: "20/08/2024",
    data_homologacao: "10/09/2024",
    economia_estimada: 15.2,
  },
  {
    id: "c5",
    numero_processo: "SES-GO/2024-003001",
    objeto: "Broncodilatadores e Corticoides Inalatórios",
    modalidade: "Pregão Eletrônico",
    valor_estimado: 6800000,
    valor_homologado: null as number | null,
    status: "planejado" as const,
    risco_atraso: "medio",
    fornecedores_habilitados: 0,
    data_abertura: "10/11/2024",
    data_homologacao: null as string | null,
    economia_estimada: 0,
  },
];

export const PDPS = [
  {
    id: "p1",
    medicamento: "Insulina Glargina",
    doenca: "Diabetes Mellitus",
    laboratorio_publico: "LAFERGS",
    laboratorio_parceiro: "LAFERGS / Sanofi-Aventis",
    empresa_privada: "Sanofi-Aventis",
    ict: "UFG / Farmacologia",
    status: "em_negociacao" as const,
    fase: "Fase II — Transferência Tecnológica",
    economia_prevista: 35,
    dependencia_externa: 100,
    prazo_autonomia: "2028",
    investimento_estimado: 45000000,
    valor_contrato: 45000000,
    vigencia_anos: 5,
    progresso_pct: 40,
    data_inicio: "Jan/2023",
    data_fim_previsto: "Dez/2028",
  },
  {
    id: "p2",
    medicamento: "Bevacizumabe (Biossimilar)",
    doenca: "Neoplasias / Oncológicos",
    laboratorio_publico: "Farmanguinhos",
    laboratorio_parceiro: "Farmanguinhos / EMS",
    empresa_privada: "EMS / Farmacêutica",
    ict: "PUC-GO / Biotecnologia",
    status: "prospeccao" as const,
    fase: "Fase I — Prospecção",
    economia_prevista: 60,
    dependencia_externa: 100,
    prazo_autonomia: "2031",
    investimento_estimado: 120000000,
    valor_contrato: 120000000,
    vigencia_anos: 8,
    progresso_pct: 10,
    data_inicio: "Jun/2024",
    data_fim_previsto: "Jun/2031",
  },
  {
    id: "p3",
    medicamento: "Trastuzumabe (Biossimilar)",
    doenca: "Neoplasias / Oncológicos",
    laboratorio_publico: "BioManguinhos",
    laboratorio_parceiro: "BioManguinhos / Cristália",
    empresa_privada: "Cristália",
    ict: "UFG / Oncologia Molecular",
    status: "aprovada" as const,
    fase: "Fase III — Produção Piloto",
    economia_prevista: 55,
    dependencia_externa: 100,
    prazo_autonomia: "2027",
    investimento_estimado: 98000000,
    valor_contrato: 98000000,
    vigencia_anos: 4,
    progresso_pct: 75,
    data_inicio: "Mar/2021",
    data_fim_previsto: "Mar/2027",
  },
  {
    id: "p4",
    medicamento: "Budesonida Inalatória",
    doenca: "Doenças Respiratórias Crônicas",
    laboratorio_publico: "IQUEGO",
    laboratorio_parceiro: "IQUEGO / EMS",
    empresa_privada: "EMS",
    ict: "UFG / Farmácia",
    status: "em_negociacao" as const,
    fase: "Fase II — Desenvolvimento",
    economia_prevista: 40,
    dependencia_externa: 75,
    prazo_autonomia: "2029",
    investimento_estimado: 28000000,
    valor_contrato: 28000000,
    vigencia_anos: 6,
    progresso_pct: 30,
    data_inicio: "Ago/2023",
    data_fim_previsto: "Ago/2029",
  },
];

export const VIABILIDADE_INDUSTRIAL = [
  {
    id: "v1",
    produto: "Metformina 850mg",
    medicamento: "Metformina 850mg",
    classe_terapeutica: "Antidiabético / Biguanida",
    viabilidade_tecnica: 92,
    viabilidade_regulatoria: 85,
    viabilidade_economica: 78,
    viabilidade_produtiva: 88,
    potencial_mercado: 85,
    dependencia_externa: 40,
    potencial_producao_local: 85,
    score_geral: 86,
    score_total: 86,
    prioridade: 1,
    status: "viavel" as const,
    investimento_necessario: 8500000,
    investimento_estimado: 8500000,
    prazo_retorno_anos: 4,
  },
  {
    id: "v2",
    produto: "Insulina NPH 100UI/mL",
    medicamento: "Insulina NPH 100UI/mL",
    classe_terapeutica: "Antidiabético / Insulina",
    viabilidade_tecnica: 75,
    viabilidade_regulatoria: 80,
    viabilidade_economica: 70,
    viabilidade_produtiva: 65,
    potencial_mercado: 72,
    dependencia_externa: 70,
    potencial_producao_local: 72,
    score_geral: 72,
    score_total: 72,
    prioridade: 2,
    status: "em_estudo" as const,
    investimento_necessario: 42000000,
    investimento_estimado: 42000000,
    prazo_retorno_anos: 7,
  },
  {
    id: "v3",
    produto: "Atorvastatina 20mg",
    medicamento: "Atorvastatina 20mg",
    classe_terapeutica: "Cardiovascular / Estatina",
    viabilidade_tecnica: 80,
    viabilidade_regulatoria: 72,
    viabilidade_economica: 60,
    viabilidade_produtiva: 55,
    potencial_mercado: 65,
    dependencia_externa: 85,
    potencial_producao_local: 65,
    score_geral: 66,
    score_total: 66,
    prioridade: 3,
    status: "em_estudo" as const,
    investimento_necessario: 15000000,
    investimento_estimado: 15000000,
    prazo_retorno_anos: 6,
  },
  {
    id: "v4",
    produto: "Bevacizumabe",
    medicamento: "Bevacizumabe",
    classe_terapeutica: "Oncológico / Anticorpo monoclonal",
    viabilidade_tecnica: 45,
    viabilidade_regulatoria: 50,
    viabilidade_economica: 55,
    viabilidade_produtiva: 35,
    potencial_mercado: 40,
    dependencia_externa: 100,
    potencial_producao_local: 40,
    score_geral: 45,
    score_total: 45,
    prioridade: 4,
    status: "em_estudo" as const,
    investimento_necessario: 120000000,
    investimento_estimado: 120000000,
    prazo_retorno_anos: 12,
  },
  {
    id: "v5",
    produto: "Budesonida Inalatória",
    medicamento: "Budesonida Inalatória",
    classe_terapeutica: "Respiratório / Corticoide",
    viabilidade_tecnica: 70,
    viabilidade_regulatoria: 68,
    viabilidade_economica: 65,
    viabilidade_produtiva: 60,
    potencial_mercado: 65,
    dependencia_externa: 75,
    potencial_producao_local: 65,
    score_geral: 66,
    score_total: 66,
    prioridade: 5,
    status: "viavel" as const,
    investimento_necessario: 22000000,
    investimento_estimado: 22000000,
    prazo_retorno_anos: 8,
  },
];

export const ALERTAS = [
  {
    id: "a1",
    titulo: "Estoque Crítico — Bevacizumabe",
    modulo: "Medicamentos",
    nivel: "critico" as const,
    descricao:
      "Estoque atual de Bevacizumabe suficiente para apenas 0,8 meses. Compra emergencial necessária. Processo SES-GO/2024-002104 fracassado.",
    data: "18/10/2024",
    responsavel: "DGAF/SES-GO",
    status: "ativo" as const,
    acao_recomendada:
      "Iniciar processo de compra emergencial via dispensa ou ata federal. Acionar Ministério da Saúde para suprimento.",
  },
  {
    id: "a2",
    titulo: "Processo Licitatório Fracassado — Oncológicos",
    modulo: "Compras",
    nivel: "critico" as const,
    descricao:
      "Pregão SES-GO/2024-002104 fracassado por falta de propostas válidas. Risco de desabastecimento em 45 dias.",
    data: "15/10/2024",
    responsavel: "DCOM/SES-GO",
    status: "em_analise" as const,
    acao_recomendada:
      "Acionar ata de registro de preço federal. Avaliar contratação direta com fundamento no Art. 75, IV da Lei 14.133/2021.",
  },
  {
    id: "a3",
    titulo: "Tendência de Crescimento — Neoplasias",
    modulo: "Epidemiológico",
    nivel: "alto" as const,
    descricao:
      "Casos de neoplasias cresceram 18% nos últimos 12 meses em Goiás. Projeção indica aumento de 23% nos próximos 24 meses.",
    data: "10/10/2024",
    responsavel: "CIEVS/SES-GO",
    status: "em_analise" as const,
    acao_recomendada:
      "Ampliar capacidade de diagnóstico precoce. Revisar estoque de medicamentos oncológicos. Iniciar negociação de PDP para biossimilares.",
  },
  {
    id: "a4",
    titulo: "Concentração de Fornecedores — Cardiovasculares",
    modulo: "Compras",
    nivel: "alto" as const,
    descricao:
      "Três fornecedores concentram 89% das compras de medicamentos cardiovasculares. Risco de oligopólio e dependência excessiva.",
    data: "08/10/2024",
    responsavel: "DCOM/SES-GO",
    status: "ativo" as const,
    acao_recomendada:
      "Ampliar base de fornecedores. Avaliar entrada de fabricantes nacionais. Negociar com laboratórios públicos.",
  },
  {
    id: "a5",
    titulo: "Oportunidade PDP — Trastuzumabe",
    modulo: "PDPs",
    nivel: "medio" as const,
    descricao:
      "PDP para Trastuzumabe com BioManguinhos em Fase III. Economia estimada de 55% no custo atual de R$ 4.200,00/unidade.",
    data: "05/10/2024",
    responsavel: "DPPI/SES-GO",
    status: "em_analise" as const,
    acao_recomendada:
      "Acompanhar cronograma da PDP. Preparar demanda para incorporação quando disponível.",
  },
  {
    id: "a6",
    titulo: "Revisão de Parâmetros — Diabetes",
    modulo: "Epidemiológico",
    nivel: "medio" as const,
    descricao:
      "Diabetes Mellitus atinge 310.000 pacientes estimados em Goiás. Taxa de controle glicêmico adequado abaixo de 40%.",
    data: "01/10/2024",
    responsavel: "CIEVS/SES-GO",
    status: "ativo" as const,
    acao_recomendada:
      "Revisar cobertura do programa de diabetes. Ampliar distribuição de glicosímetros e tiras-teste.",
  },
  {
    id: "a7",
    titulo: "Estoque Regular — Metformina",
    modulo: "Medicamentos",
    nivel: "baixo" as const,
    descricao:
      "Metformina 850mg com estoque para 4,8 meses. Dentro do parâmetro seguro (>3 meses). Produção nacional garantida.",
    data: "28/09/2024",
    responsavel: "DGAF/SES-GO",
    status: "resolvido" as const,
    acao_recomendada: "Manter monitoramento mensal padrão.",
  },
];

export const INDICADORES_DASHBOARD = {
  total_doencas_monitoradas: 6,
  total_medicamentos_estrategicos: 42,
  medicamentos_criticos: 3,
  medicamentos_em_risco: 5,
  valor_total_compras_ano: 187500000,
  economia_gerada_ano: 23400000,
  pdps_ativas: 4,
  pdps_prospeccao: 8,
  alertas_criticos: 2,
  alertas_total: 7,
  cobertura_populacao_pct: 78.4,
  municipios_monitorados: 246,
};

export const EVOLUCAO_TEMPORAL = [
  { mes: "Jan/24", cardiovascular: 220, diabetes: 280, oncologico: 38, mental: 165, respiratorio: 115 },
  { mes: "Fev/24", cardiovascular: 225, diabetes: 285, oncologico: 39, mental: 168, respiratorio: 118 },
  { mes: "Mar/24", cardiovascular: 228, diabetes: 292, oncologico: 40, mental: 172, respiratorio: 122 },
  { mes: "Abr/24", cardiovascular: 232, diabetes: 295, oncologico: 41, mental: 175, respiratorio: 120 },
  { mes: "Mai/24", cardiovascular: 235, diabetes: 300, oncologico: 42, mental: 178, respiratorio: 124 },
  { mes: "Jun/24", cardiovascular: 238, diabetes: 302, oncologico: 42, mental: 180, respiratorio: 126 },
  { mes: "Jul/24", cardiovascular: 240, diabetes: 306, oncologico: 41, mental: 182, respiratorio: 127 },
  { mes: "Ago/24", cardiovascular: 242, diabetes: 308, oncologico: 42, mental: 183, respiratorio: 128 },
  { mes: "Set/24", cardiovascular: 244, diabetes: 309, oncologico: 42, mental: 184, respiratorio: 127 },
  { mes: "Out/24", cardiovascular: 248, diabetes: 310, oncologico: 42, mental: 185, respiratorio: 128 },
];

export const REGIONAIS_SAUDE = [
  { id: "r1", nome: "Goiânia", municipios: 26, populacao: 1_800_000, cobertura_pct: 92 },
  { id: "r2", nome: "Anápolis", municipios: 22, populacao: 620_000, cobertura_pct: 85 },
  { id: "r3", nome: "Rio Verde", municipios: 18, populacao: 380_000, cobertura_pct: 78 },
  { id: "r4", nome: "Catalão", municipios: 14, populacao: 220_000, cobertura_pct: 72 },
  { id: "r5", nome: "Jataí", municipios: 16, populacao: 180_000, cobertura_pct: 68 },
  { id: "r6", nome: "Ceres", municipios: 20, populacao: 290_000, cobertura_pct: 74 },
  { id: "r7", nome: "Itumbiara", municipios: 12, populacao: 165_000, cobertura_pct: 70 },
  { id: "r8", nome: "Uruaçu", municipios: 18, populacao: 145_000, cobertura_pct: 65 },
  { id: "r9", nome: "Porangatu", municipios: 24, populacao: 185_000, cobertura_pct: 62 },
  { id: "r10", nome: "São Luís de Montes Belos", municipios: 16, populacao: 120_000, cobertura_pct: 60 },
  { id: "r11", nome: "Iporá", municipios: 14, populacao: 95_000, cobertura_pct: 58 },
  { id: "r12", nome: "Rubiataba", municipios: 10, populacao: 88_000, cobertura_pct: 55 },
  { id: "r13", nome: "Formosa", municipios: 10, populacao: 180_000, cobertura_pct: 70 },
];
